### ISSUE TITLE
Uncaught TypeError: Object #<File> has no method 'slice'

### ISSUE THREAD

**Issue by andrewhavens** [thirtysixthspan/waterunderice#1]
I'm using Google Chrome version 17.0.963.56. I'm getting this error in the Developer console when I try to upload a file:

```
Uncaught TypeError: Object #<File> has no method 'slice'
web_socket_file_uploader.js:141
```

Do you know why this could be?

**Comment by thirtysixthspan** [comment]
Looks like the FileAPI is evolving -  See: 

https://groups.google.com/a/chromium.org/group/chromium-html5/browse_thread/thread/2c963f6ecdae0573?pli=1

You might try webkitSlice instead.
